nv]
PYTHON_VERSION = "3.12"

[phases.setup]
packages = [
  "python3.12",
  "python3.12Packages.distutils",
  "gcc",
  "libffi",
]

[phases.install]
commands = [
  "python -m venv --copies /opt/venv",
  ". /opt/venv/bin/activate",
  "pip install --upgrade pip setuptools wheel",
  "pip install -r requirements.txt"
]

[phases.start]
commands = [
  "uvicorn calling_api_ve:app --host 0.0.0.0 --port $PORT"
]

